### ISSUE TITLE
Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by All4Gis** [bor8/docker-qgis-server-qwc2#1]
Good job

I'm modifying it to improve some things, but I have a problem with the original project

When I put my ip it seems the error:

```

> ERROR reading WMS GetProjectSettings of https://85.58.144.26/cgi-bin/project/qgis_mapserv.fcgi:
> client_1  |  { Error: connect ECONNREFUSED 85.58.144.26:80
> client_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
> client_1  |   errno: 'ECONNREFUSED',
> client_1  |   code: 'ECONNREFUSED',
> client_1  |   syscall: 'connect',
> client_1  |   address: '85.58.144.26',
> client_1  |   port: 80,
> client_1  |   config:
> 

```
Has it ever happened? work on windows 10

server and client work perfectly but not to access to my project

**Comment by bor8** [comment]
You're welcome. :)

HTTP normally runs on port 80. HTTPS normally runs on port 443. Maybe you can tweak this.

**Comment by All4Gis** [comment]
I will try using http and nothing!connection refused.

This docker work in your machine?I guess so

**Comment by bor8** [comment]
I think I only tested it on Mac or Ubuntu. That's where it worked. I might check it out tonight for Windows 10.

**Comment by All4Gis** [comment]
thanks,for work on windows this lines not work,

https://github.com/bor8/docker-qgis-server-qwc2/blob/master/server/Dockerfile#L16

you need change to 

```
RUN echo "deb http://qgis.org/debian-ltr stretch main" >> /etc/apt/sources.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key CAEB3DC3BDF7FB45
RUN apt-get update && apt-get install -y qgis-server

RUN apt-get install -y python-qgis apache2 libapache2-mod-fcgid unzip --force-yes
```

**Comment by All4Gis** [comment]
Could you try it on windows?thanks

**Comment by bor8** [comment]
It works for me. I took the IP that ipconfig shows me. Want me to take some screenshots? Or a screencast?

**Comment by All4Gis** [comment]
mmm..it's so strange,it works for you without making any changes, just the ip?maybe i have a conflict with ports..I don't know,attach a screen if you can

**Comment by bor8** [comment]
https://youtu.be/S1lsrcswJEI

**Comment by All4Gis** [comment]
thanks for this video, I don't understand but not work.
I'm using a clean windows computer and not work

```
client_1  | ERROR reading WMS GetProjectSettings of http://192.168.1.111/cgi-bin/qgis_mapserv.fcgi:
client_1  |  { Error: socket hang up
client_1  |     at createHangUpError (_http_client.js:342:15)
client_1  |     at Socket.socketOnEnd (_http_client.js:437:23)
client_1  |     at emitNone (events.js:111:20)
client_1  |     at Socket.emit (events.js:208:7)
client_1  |     at endReadableNT (_stream_readable.js:1064:12)
client_1  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
client_1  |     at process._tickCallback (internal/process/next_tick.js:181:9)
client_1  |   code: 'ECONNRESET',
```

Did you do any docker settings? I'm not under a proxy or anything

I don't understand

**Comment by All4Gis** [comment]
Finaly work,but i need make a link on client app to server!Working! thanks
